name: Build OpenWrt

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Initialization environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint

    - name: Clone source code
      run: |
        git clone https://github.com/coolsnowwolf/lede
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        ln -sf $GITHUB_WORKSPACE/packages $GITHUB_WORKSPACE/lede/package/diy-packages
        ln -sf $GITHUB_WORKSPACE/files $GITHUB_WORKSPACE/lede/files
        sed -i 's/OpenWrt/P3TERX build $(date "+%Y.%m.%d") @ OpenWrt/g' $GITHUB_WORKSPACE/lede/package/lean/default-settings/files/zzz-default-settings
        sed -i 's/luci-theme-bootstrap/luci-theme-argon/g' $GITHUB_WORKSPACE/lede/feeds/luci/collections/luci/Makefile
        chmod +x diy.sh
        ./diy.sh
        cp .config lede
        cd lede
        make defconfig

    - name: Download package
      run: |
        cd lede && make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Build
      run: |
        cd lede
        echo -e "$(nproc) thread build"
        make -j$(nproc) V=s

    - name: Organize files
      run: |
        cp lede/bin/targets/ramips/mt7621/openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin P3TERX-openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
        sha256sum P3TERX* > sha256sums.txt
        cd lede/bin && zip -r $GITHUB_WORKSPACE/OpenWrt-Newifi-D2.zip *

    - name: Upload to release
      uses: meeDamian/github-release@1.0
      with:
        token: ${{ secrets.OPENWRT_TOKEN }}
        gzip: false
        files: >
          OpenWrt-Newifi-D2.zip
          sha256sums.txt
          P3TERX-openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin
        allow_override: true